# fly.toml app configuration file generated for mmo-game-server on 2025-07-17T09:36:08-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

command = "node game_server.js"

app = 'mmo-game-server'
primary_region = 'yyz'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
